[project]
name = "sirbalo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.4",
    "fastapi>=0.116.1",
    "orjson>=3.11.1",
    "pillow>=11.3.0",
]
